## Exercise L3 - 1: Diagnose Dataset Level and Select Last Encounter

### Instructions
- Given the dataset, convert the dataset to a longitudinal level but select only the last encounter for each patient.
- Assume that that the order of encounter IDs is indicative of the time for encounter. In other words a lower number encounter will come before a higher numbered encounter.

In [1]:
import pandas as pd
import numpy as np

In [2]:
ehr_level_dataset_path = "./data/ehr_level_exercise_dataset.csv"

### Level of Dataset
What level is the dataset at? Is at the line or encounter level?

### Solution

In [3]:
ehr_level_df = pd.read_csv(ehr_level_dataset_path)
ehr_level_df.head()

,ENCOUNTER_ID,PATIENT_ID,PRINCIPAL_DIAGNOSIS_CODE,PROCEDURE_CODE,MEDICATION_CODE,LAB_CODE,LABEL
0,udacity_health_encounter_id_1,udacity_health_patient_id_186,dx_code_15406,"['procedure_code_58552', 'procedure_code_39776...","['medication_code_2350', 'medication_code_8630...","['lab_code_8835', 'lab_code_9859', 'lab_code_9...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,udacity_health_encounter_id_10,udacity_health_patient_id_188,dx_code_74047,[],"['medication_code_7789', 'medication_code_3560...",[],"[1, 1, 1, 1]"
2,udacity_health_encounter_id_100,udacity_health_patient_id_585,dx_code_71465,[],"['medication_code_7982', 'medication_code_2452...","['lab_code_4198', 'lab_code_6603', 'lab_code_3...","[0, 0, 0, 0, 0, 0, 0]"
3,udacity_health_encounter_id_1000,udacity_health_patient_id_525,dx_code_61569,[],['medication_code_4036'],[],[0]
4,udacity_health_encounter_id_1001,udacity_health_patient_id_950,dx_code_90172,['procedure_code_30555'],"['medication_code_6755', 'medication_code_5045']",['lab_code_9112'],"[0, 0, 0, 0]"

**Tests**
- Line: Total number of rows > Number of Unique Encounters
- Encounter level: Total Number of Rows = Number of Unique Encounters

In [4]:
# Line Test
try:
    assert len(ehr_level_df) > ehr_level_df['ENCOUNTER_ID'].nunique() 
    print("Dataset could be at the line level")
except:
    print("Dataset is not at the line level")

Dataset is not at the line level

In [5]:
# Encounter Test
try:
    assert len(ehr_level_df) == ehr_level_df['ENCOUNTER_ID'].nunique()
    print("Dataset could be at the encounter level")
except:
    print("Dataset is not at the encounter level")

Dataset could be at the encounter level

**Answer:** Dataset is at the encounter level and you can probably guess by seeing the arrays for the code sets but we did a few simple tests to confirm.

### Select Last Encounter for each Patient

So in many cases you may only want a snapshot of a patient's history for your modeling objective. In some cases it might be important to see the changes over time but in other cases you only want the most recent case or depending on the model the first case could also be used. Really important to know how the context for how the model will be deployed in production and the time state you will be getting data.

In [6]:
# select last encounter for each patient
#convert encounter id column to a numerical value
def convert_encounter_id_to_number(df, encounter_id):
    df["ENCOUNTER_ID_NUMBER"] = df[encounter_id].str.replace('udacity_health_encounter_id_', '').astype(int)
    return df

def select_last_encounter(df, patient_id, encounter_id):
    df = df.sort_values(encounter_id)
    last_encounter_values = df.groupby(patient_id)[encounter_id].tail(1).values
    return df[df[encounter_id].isin(last_encounter_values)]

In [7]:
ehr_encounter_number_df = convert_encounter_id_to_number(ehr_level_df, "ENCOUNTER_ID")
last_encounter_df = select_last_encounter(ehr_encounter_number_df, "PATIENT_ID", "ENCOUNTER_ID_NUMBER" )

In [8]:
#take subset of output
test_last_encounter_df = last_encounter_df[['ENCOUNTER_ID', 'ENCOUNTER_ID_NUMBER', 'PATIENT_ID']]

### Test cases 
- PATIENT_IDS - udacity_health_patient_id_309, udacity_health_patient_id_418, udacity_health_patient_id_908

In [9]:
ehr_level_df[ehr_level_df['PATIENT_ID']=='udacity_health_patient_id_309']

,ENCOUNTER_ID,PATIENT_ID,PRINCIPAL_DIAGNOSIS_CODE,PROCEDURE_CODE,MEDICATION_CODE,LAB_CODE,LABEL,ENCOUNTER_ID_NUMBER
94,udacity_health_encounter_id_1091,udacity_health_patient_id_309,dx_code_62502,['procedure_code_69597'],"['medication_code_9253', 'medication_code_7444...","['lab_code_9415', 'lab_code_8179']","[0, 0, 0, 0, 0, 0, 0]",1091
450,udacity_health_encounter_id_1436,udacity_health_patient_id_309,dx_code_37825,"['procedure_code_14044', 'procedure_code_47911...","['medication_code_4081', 'medication_code_6050...","['lab_code_6246', 'lab_code_7197']","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1436
605,udacity_health_encounter_id_1582,udacity_health_patient_id_309,dx_code_79663,[],"['medication_code_4450', 'medication_code_4900...",[],"[0, 0, 0]",1582
665,udacity_health_encounter_id_1643,udacity_health_patient_id_309,dx_code_60773,"['procedure_code_39999', 'procedure_code_31842...","['medication_code_413', 'medication_code_5966'...","['lab_code_4295', 'lab_code_2383']","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1643
684,udacity_health_encounter_id_1662,udacity_health_patient_id_309,dx_code_29272,"['procedure_code_12589', 'procedure_code_3005'...","['medication_code_9845', 'medication_code_6602...","['lab_code_4330', 'lab_code_3499', 'lab_code_1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1662
867,udacity_health_encounter_id_1837,udacity_health_patient_id_309,dx_code_56368,"['procedure_code_14069', 'procedure_code_15230...","['medication_code_5820', 'medication_code_8028...",['lab_code_8964'],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1837
1024,udacity_health_encounter_id_1985,udacity_health_patient_id_309,dx_code_38581,"['procedure_code_1431', 'procedure_code_71061']","['medication_code_3134', 'medication_code_4868...",['lab_code_7702'],"[0, 0, 0, 0, 0, 0, 0, 0, 0]",1985
1042,udacity_health_encounter_id_2000,udacity_health_patient_id_309,dx_code_91230,[],[],['lab_code_8062'],[0],2000
1196,udacity_health_encounter_id_2142,udacity_health_patient_id_309,dx_code_58527,"['procedure_code_56979', 'procedure_code_24797...","['medication_code_7631', 'medication_code_7508...","['lab_code_3908', 'lab_code_1500']","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2142
1289,udacity_health_encounter_id_2229,udacity_health_patient_id_309,dx_code_46826,"['procedure_code_50916', 'procedure_code_20032...","['medication_code_9204', 'medication_code_1282...","['lab_code_5607', 'lab_code_5139']","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",2229
1340,udacity_health_encounter_id_2281,udacity_health_patient_id_309,dx_code_39484,"['procedure_code_33400', 'procedure_code_56', ...","['medication_code_1938', 'medication_code_4076...","['lab_code_9178', 'lab_code_3557', 'lab_code_2...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",2281
1596,udacity_health_encounter_id_2531,udacity_health_patient_id_309,dx_code_75423,"['procedure_code_15600', 'procedure_code_19008...","['medication_code_7265', 'medication_code_2247...","['lab_code_8336', 'lab_code_7292', 'lab_code_8...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2531
1702,udacity_health_encounter_id_2631,udacity_health_patient_id_309,dx_code_38210,['procedure_code_121'],"['medication_code_7480', 'medication_code_7917...",['lab_code_4777'],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",2631
2069,udacity_health_encounter_id_2989,udacity_health_patient_id_309,dx_code_80145,"['procedure_code_28893', 'procedure_code_9124'...","['medication_code_43', 'medication_code_5602',...","['lab_code_3392', 'lab_code_9665', 'lab_code_4...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2989
2291,udacity_health_encounter_id_3209,udacity_health_patient_id_309,dx_code_74710,"['procedure_code_41970', 'procedure_code_64032...","['medication_code_7596', 'medication_code_7481...",['lab_code_9105'],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",3209
2507,udacity_health_encounter_id_3416,udacity_health_patient_id_309,dx_code_43343,"['procedure_code_11834', 'procedure_code_12304...","['medication_code_3767', 'medication_code_7630...","['lab_code_774', 'lab_code_9591', 'lab_code_31...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",3416
2696,udacity_health_encounter_id_360,udacity_health_patient_id_309,dx_code_94868,[],"['medication_code_193', 'medication_code_3556'...",[],"[0, 0, 0]",360
2890,udacity_health_encounter_id_3792,udacity_health_patient_id_309,dx_code_37738,"['procedure_code_11852', 'procedure_code_45278...","['medication_code_7882', 'medication_code_6562...","['lab_code_3787', 'lab_code_6452', 'lab_code_6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",3792
2960,udacity_health_encounter_id_3859,udacity_health_patient_id_309,dx_code_17144,['procedure_code_69917'],"['medication_code_2152', 'medication_code_7078...",['lab_code_5682'],"[0, 0, 0, 0, 0, 0, 0]",3859
3064,udacity_health_encounter_id_3961,udacity_health_patient_id_309,dx_code_61465,"['procedure_code_15248', 'procedure_code_65724...","['medication_code_701', 'medication_code_8324'...","['lab_code_7691', 'lab_code_4598', 'lab_code_1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",3961
3167,udacity_health_encounter_id_4058,udacity_health_patient_id_309,dx_code_73636,"['procedure_code_5646', 'procedure_code_1381',...","['medication_code_4201', 'medication_code_5328...","['lab_code_9083', 'lab_code_1392', 'lab_code_1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4058
3280,udacity_health_encounter_id_4168,udacity_health_patient_id_309,dx_code_9795,"['procedure_code_44804', 'procedure_code_10917...","['medication_code_2738', 'medication_code_9919...","['lab_code_4690', 'lab_code_5570', 'lab_code_2...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4168
3353,udacity_health_encounter_id_4239,udacity_health_patient_id_309,dx_code_28764,"['procedure_code_31873', 'procedure_code_29930...","['medication_code_7607', 'medication_code_6643...","['lab_code_8492', 'lab_code_3309', 'lab_code_6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4239
3561,udacity_health_encounter_id_4439,udacity_health_patient_id_309,dx_code_31393,"['procedure_code_69203', 'procedure_code_53820...","['medication_code_9780', 'medication_code_7008...",[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]",4439
3585,udacity_health_encounter_id_4462,udacity_health_patient_id_309,dx_code_53624,"['procedure_code_64278', 'procedure_code_19230']","['medication_code_8759', 'medication_code_59',...","['lab_code_3790', 'lab_code_591', 'lab_code_89...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4462
3718,udacity_health_encounter_id_4589,udacity_health_patient_id_309,dx_code_67438,[],['medication_code_8103'],[],[0],4589
3752,udacity_health_encounter_id_4619,udacity_health_patient_id_309,dx_code_79460,"['procedure_code_8648', 'procedure_code_22388'...","['medication_code_4773', 'medication_code_5839...",['lab_code_5055'],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",4619
3916,udacity_health_encounter_id_478,udacity_health_patient_id_309,dx_code_43778,[],"['medication_code_1646', 'medication_code_4346']",[],"[0, 0]",478
4552,udacity_health_encounter_id_5398,udacity_health_patient_id_309,dx_code_58513,"['procedure_code_3629', 'procedure_code_56509'...","['medication_code_5697', 'medication_code_9845...",['lab_code_4909'],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",5398
4687,udacity_health_encounter_id_553,udacity_health_patient_id_309,dx_code_88408,"['procedure_code_19471', 'procedure_code_17060...","['medication_code_1541', 'medication_code_5218...","['lab_code_4271', 'lab_code_7946', 'lab_code_9...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",553
4771,udacity_health_encounter_id_5611,udacity_health_patient_id_309,dx_code_46410,"['procedure_code_71656', 'procedure_code_29912...","['medication_code_3365', 'medication_code_862'...","['lab_code_8280', 'lab_code_9803', 'lab_code_1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",5611
4785,udacity_health_encounter_id_5624,udacity_health_patient_id_309,dx_code_96267,[],['medication_code_1343'],['lab_code_9589'],"[0, 0]",5624
4796,udacity_health_encounter_id_5635,udacity_health_patient_id_309,dx_code_67422,[],['medication_code_2864'],[],[0],5635
4862,udacity_health_encounter_id_5701,udacity_health_patient_id_309,dx_code_4007,"['procedure_code_8263', 'procedure_code_7509']","['medication_code_3925', 'medication_code_3163']",[],"[0, 0, 0, 0]",5701
4881,udacity_health_encounter_id_5721,udacity_health_patient_id_309,dx_code_11147,"['procedure_code_68127', 'procedure_code_3768'...","['medication_code_4722', 'medication_code_2681...","['lab_code_8853', 'lab_code_3111', 'lab_code_2...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",5721
5132,udacity_health_encounter_id_597,udacity_health_patient_id_309,dx_code_25907,"['procedure_code_41138', 'procedure_code_28596']","['medication_code_4777', 'medication_code_4318...",['lab_code_1043'],"[0, 0, 0, 0, 0, 0]",597
5306,udacity_health_encounter_id_6139,udacity_health_patient_id_309,dx_code_40784,"['procedure_code_48973', 'procedure_code_7953'...","['medication_code_3191', 'medication_code_105'...","['lab_code_5078', 'lab_code_2361', 'lab_code_9...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6139
5385,udacity_health_encounter_id_622,udacity_health_patient_id_309,dx_code_25556,['procedure_code_10462'],"['medication_code_3626', 'medication_code_311']",['lab_code_4960'],"[0, 0, 0, 0]",622
5472,udacity_health_encounter_id_6305,udacity_health_patient_id_309,dx_code_93595,"['procedure_code_6005', 'procedure_code_13203'...",['medication_code_4513'],"['lab_code_7349', 'lab_code_1043', 'lab_code_9...","[0, 0, 0, 0, 0, 0, 0]",6305
5564,udacity_health_encounter_id_6394,udacity_health_patient_id_309,dx_code_17875,['procedure_code_42424'],[],['lab_code_5222'],"[0, 0]",6394
5669,udacity_health_encounter_id_6497,udacity_health_patient_id_309,dx_code_36095,"['procedure_code_33881', 'procedure_code_6396'...","['medication_code_6849', 'medication_code_2364...","['lab_code_2570', 'lab_code_2383', 'lab_code_8...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",6497
5684,udacity_health_encounter_id_6512,udacity_health_patient_id_309,dx_code_92784,"['procedure_code_31090', 'procedure_code_28839...","['medication_code_5274', 'medication_code_6976...",['lab_code_4639'],"[0, 0, 0, 0, 0, 0, 0, 0, 0]",6512
5829,udacity_health_encounter_id_6662,udacity_health_patient_id_309,dx_code_26279,"['procedure_code_47253', 'procedure_code_52416...","['medication_code_2602', 'medication_code_3320...",['lab_code_5441'],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",6662
5846,udacity_health_encounter_id_668,udacity_health_patient_id_309,dx_code_22666,"['procedure_code_10507', 'procedure_code_39636...","['medication_code_4676', 'medication_code_4760...","['lab_code_7518', 'lab_code_1774', 'lab_code_5...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",668
5946,udacity_health_encounter_id_6777,udacity_health_patient_id_309,dx_code_78269,"['procedure_code_58888', 'procedure_code_72745']","['medication_code_227', 'medication_code_7799']",[],"[0, 0, 0, 0]",6777
6508,udacity_health_encounter_id_7327,udacity_health_patient_id_309,dx_code_18813,"['procedure_code_9329', 'procedure_code_28542'...","['medication_code_4006', 'medication_code_485'...","['lab_code_71', 'lab_code_7769', 'lab_code_659...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7327
6892,udacity_health_encounter_id_7696,udacity_health_patient_id_309,dx_code_24785,"['procedure_code_31137', 'procedure_code_23811...","['medication_code_2626', 'medication_code_6310...","['lab_code_8317', 'lab_code_2116', 'lab_code_2...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7696
6969,udacity_health_encounter_id_7772,udacity_health_patient_id_309,dx_code_949,"['procedure_code_45976', 'procedure_code_26419...","['medication_code_9684', 'medication_code_8486...",[],"[0, 0, 0, 0, 0, 0, 0]",7772
7217,udacity_health_encounter_id_995,udacity_health_patient_id_309,dx_code_4976,"['procedure_code_8156', 'procedure_code_23220']","['medication_code_5388', 'medication_code_5533...",['lab_code_2049'],"[0, 0, 0, 0, 0, 0, 0]",995

For patient id 309, the selected encounter should be 7772.

In [10]:
test_last_encounter_df[test_last_encounter_df['PATIENT_ID']=='udacity_health_patient_id_309']

,ENCOUNTER_ID,ENCOUNTER_ID_NUMBER,PATIENT_ID
6969,udacity_health_encounter_id_7772,7772,udacity_health_patient_id_309

In [11]:
ehr_level_df[ehr_level_df['PATIENT_ID']=='udacity_health_patient_id_418']

,ENCOUNTER_ID,PATIENT_ID,PRINCIPAL_DIAGNOSIS_CODE,PROCEDURE_CODE,MEDICATION_CODE,LAB_CODE,LABEL,ENCOUNTER_ID_NUMBER
263,udacity_health_encounter_id_1258,udacity_health_patient_id_418,dx_code_87320,[],['medication_code_7475'],[],[0],1258
1230,udacity_health_encounter_id_2173,udacity_health_patient_id_418,dx_code_72104,"['procedure_code_37393', 'procedure_code_48757...","['medication_code_3809', 'medication_code_9141...","['lab_code_2839', 'lab_code_2665', 'lab_code_3...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2173
2448,udacity_health_encounter_id_3362,udacity_health_patient_id_418,dx_code_77979,['procedure_code_64397'],"['medication_code_2807', 'medication_code_6979']",[],"[0, 0, 0]",3362

For patient id 418, the selected encounter should be 3362.

In [12]:
test_last_encounter_df[test_last_encounter_df['PATIENT_ID']=='udacity_health_patient_id_418']

,ENCOUNTER_ID,ENCOUNTER_ID_NUMBER,PATIENT_ID
2448,udacity_health_encounter_id_3362,3362,udacity_health_patient_id_418

In [13]:
ehr_level_df[ehr_level_df['PATIENT_ID']=='udacity_health_patient_id_908']

,ENCOUNTER_ID,PATIENT_ID,PRINCIPAL_DIAGNOSIS_CODE,PROCEDURE_CODE,MEDICATION_CODE,LAB_CODE,LABEL,ENCOUNTER_ID_NUMBER
1678,udacity_health_encounter_id_2608,udacity_health_patient_id_908,dx_code_52877,[],['medication_code_6189'],[],[0],2608
2796,udacity_health_encounter_id_3698,udacity_health_patient_id_908,dx_code_52688,['procedure_code_60912'],[],"['lab_code_4691', 'lab_code_9380']","[0, 0, 0]",3698
5301,udacity_health_encounter_id_6132,udacity_health_patient_id_908,dx_code_36066,"['procedure_code_5724', 'procedure_code_55191'...","['medication_code_9532', 'medication_code_3398...","['lab_code_9732', 'lab_code_2808', 'lab_code_3...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",6132
7131,udacity_health_encounter_id_910,udacity_health_patient_id_908,dx_code_98539,"['procedure_code_8188', 'procedure_code_59872'...","['medication_code_5112', 'medication_code_3537...",[],"[0, 0, 0, 0, 0, 0, 0]",910

For patient id 908, the selected encounter should be 6132.

In [14]:
test_last_encounter_df[test_last_encounter_df['PATIENT_ID']=='udacity_health_patient_id_908']

,ENCOUNTER_ID,ENCOUNTER_ID_NUMBER,PATIENT_ID
5301,udacity_health_encounter_id_6132,6132,udacity_health_patient_id_908

## Exercise  L3 - 2: Dataset Splitting

### Instructions
- Split the provided dataset into a train and test split but be sure not to mix patient encounter records across the two partitions
- Be sure to run the following three tests
    - Patient data in only one partition
    - Total unique number of patients across all partitions = total number unique patients in original full dataset
    - Total number of rows original dataset = sum of rows across splits

In [15]:
splitting_exercise_dataset_path = "./data/SYNTHETIC_EHR_DATASET.csv"

### Solution

This is largely a review of two parts in this lesson and you can use most of the same code for each step. The key is to identify the level of the dataset and then to convert it to the encounter level before you do your splits. Then perform the splitting and run the tests.

#### Convert to Encounter Level

In [16]:
# convert to encounter and then split but make sure 
ehr_pre_split_df = pd.read_csv(splitting_exercise_dataset_path)
grouping_field_list = ['ENCOUNTER_ID', 'PATIENT_ID', 'PRINCIPAL_DIAGNOSIS_CODE']
non_grouped_field_list = [c for c in ehr_pre_split_df.columns if c not in grouping_field_list]
ehr_encounter_df = ehr_pre_split_df.groupby(grouping_field_list)[non_grouped_field_list].agg(lambda x: 
                                                        list([y for y in x if y is not np.nan ] ) ).reset_index()

#### Split at Patient Level

In [17]:
PATIENT_ID_FIELD = 'PATIENT_ID'
TEST_PERCENTAGE = 0.2

In [18]:
def split_dataset_patient_level(df, key, test_percentage=0.2):
    df = df.iloc[np.random.permutation(len(df))]
    unique_values = df[key].unique()
    total_values = len(unique_values)
    sample_size = round(total_values * (1 - test_percentage ))
    train = df[df[key].isin(unique_values[:sample_size])].reset_index(drop=True)
    test = df[df[key].isin(unique_values[sample_size:])].reset_index(drop=True)
    return train, test

In [19]:
train_df, test_df = split_dataset_patient_level(ehr_encounter_df, PATIENT_ID_FIELD, TEST_PERCENTAGE)

In [20]:
assert len(set(train_df[PATIENT_ID_FIELD].unique()).intersection(set(test_df[PATIENT_ID_FIELD].unique()))) == 0
print("Test passed for patient data in only one partition")

Test passed for patient data in only one partition

In [21]:
assert (train_df[PATIENT_ID_FIELD].nunique()  + test_df[PATIENT_ID_FIELD].nunique()) == ehr_encounter_df[PATIENT_ID_FIELD].nunique()
print("Test passed for number of unique patients being equal!")

Test passed for number of unique patients being equal!

In [22]:
assert len(train_df)  + len(test_df) == len(ehr_encounter_df)
print("Test passed for number of total rows equal!")

Test passed for number of total rows equal!

#### Optional
- Check label distribution and use scikitlearn - https://scikit-learn.org/stable/auto_examples/model_selection/plot_cv_indices.html#sphx-glr-auto-examples-model-selection-plot-cv-indices-py

## Exercise  L3 - 3: Build Bucketed Numeric Feature with TF

### Instructions
- Given the Swiss heart disease dataset that we worked with earlier, build a bucketed numeric feature from the age feature. 
- For this exercise, use the Tensorflow csv function for loading the dataset directly into a TF tensor -https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_csv_dataset. This approach will be useful for when you have much larger datasets and also allows you to bypass loading the dataset in Pandas.
- More information on the Tensorflow bucketized feature can be found here https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column. Bucketed features take as input the  numeric feature that we covered in the lesson. For the numeric feature, you do not need to normalize it like we did in the lesson.

In [23]:
import tensorflow as tf
swiss_dataset_path = "./data/lesson_exercise_swiss_dataset.csv"
BATCH_SIZE =128
PREDICTOR_FIELD = 'num_label'

### Solution

In [24]:
# ETL with TF dataset make csv function
swiss_tf_dataset = tf.data.experimental.make_csv_dataset( swiss_dataset_path, batch_size=BATCH_SIZE, 
                                                         num_epochs=1, label_name=PREDICTOR_FIELD, header=True)

In [25]:
swiss_dataset_batch = next(iter(swiss_tf_dataset))[0]
swiss_dataset_batch

OrderedDict([('age',
              <tf.Tensor: shape=(123,), dtype=int32, numpy=
              array([50, 54, 61, 53, 56, 42, 72, 65, 64, 38, 38, 52, 57, 55, 63, 55, 53,
                     66, 43, 38, 58, 69, 38, 53, 57, 65, 59, 54, 65, 51, 70, 65, 67, 56,
                     61, 61, 32, 59, 53, 46, 56, 47, 61, 47, 57, 55, 63, 62, 60, 60, 62,
                     60, 73, 56, 51, 38, 42, 60, 36, 62, 51, 62, 61, 34, 56, 40, 56, 57,
                     43, 54, 60, 52, 53, 50, 61, 43, 58, 68, 68, 57, 74, 50, 70, 59, 46,
                     61, 53, 58, 61, 53, 50, 62, 60, 59, 35, 64, 57, 64, 69, 51, 45, 51,
                     66, 55, 61, 56, 63, 52, 51, 41, 63, 47, 48, 53, 51, 59, 56, 38, 62,
                     52, 62, 63, 47], dtype=int32)>)])

In [26]:
# create TF numeric feature
tf_numeric_age_feature = tf.feature_column.numeric_column(key='age', default_value=0, dtype=tf.float64)

In [27]:
#boundaries for the different age buckets
b_list = [ 0, 18, 25, 40, 55, 65, 80, 100]
#create TF bucket feature from numeric feature
tf_bucket_age_feature = tf.feature_column.bucketized_column(source_column=tf_numeric_age_feature, boundaries= b_list)

In [28]:
def demo(feature_column, example_batch):
    feature_layer = tf.keras.layers.DenseFeatures(feature_column)
    print(feature_layer(example_batch))
    print("\nExample of one transformed row:")
    print(feature_layer(example_batch).numpy()[0])

In [29]:
print("Example bucket field:\n{}\n".format(tf_bucket_age_feature))
demo(tf_bucket_age_feature, swiss_dataset_batch)

Example bucket field:
BucketizedColumn(source_column=NumericColumn(key='age', shape=(1,), default_value=(0,), dtype=tf.float64, normalizer_fn=None), boundaries=(0, 18, 25, 40, 55, 65, 80, 100))

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(123, 9), dtype=float32)

Example of one transformed row:
[0. 0. 0. 0. 1. 0. 0. 0. 0.]

## Exercise  L3 - 4:  Build Embedding Categorical Feature with TF

### Instructions
- Build a 10 dimension embedding feature for the PRINCIPAL_DIAGNOSIS_CODE field
- Here is the link to the Tensorflow Embedding column documentation -https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column
- Some functions provided below to assist

In [30]:
ehr_line_df = pd.read_csv("./data/SYNTHETIC_EHR_DATASET.csv")
cat_example_df = ehr_line_df[['ENCOUNTER_ID', 'PRINCIPAL_DIAGNOSIS_CODE', 'LABEL']]

In [31]:
#adapted from https://www.tensorflow.org/tutorials/structured_data/feature_columns
def df_to_dataset(df, predictor,  batch_size=32):
    df = df.copy()
    labels = df.pop(predictor)
    ds = tf.data.Dataset.from_tensor_slices((dict(df), labels))
    ds = ds.shuffle(buffer_size=len(df))
    ds = ds.batch(batch_size)
    return ds

In [32]:
BATCH_SIZE = 64
PREDICTOR_FIELD = 'LABEL'
categorical_tf_ds = df_to_dataset(cat_example_df, PREDICTOR_FIELD, batch_size=BATCH_SIZE)

In [33]:
# build vocab for categorical features
def write_vocabulary_file(vocab_list, field_name, default_value, vocab_dir='./vocab/'):
    output_file_path = os.path.join(vocab_dir, str(field_name) + "_vocab.txt")
    # put default value in first row as TF requires
    vocab_list = np.insert(vocab_list, 0, default_value, axis=0) 
    df = pd.DataFrame(vocab_list).to_csv(output_file_path, index=None, header=None)
    return output_file_path

def build_vocab_files(df, categorical_column_list, default_value='00'):
    vocab_files_list = []
    for c in categorical_column_list:
        v_file = write_vocabulary_file(df[c].unique(), c, default_value)
        vocab_files_list.append(v_file)
    return vocab_files_list

### Solution

In [34]:
import os
# add logic to add if not exist
#os.mkdir("./vocab/")

In [35]:
categorical_field_list = ["PRINCIPAL_DIAGNOSIS_CODE"]
vocab_files_list = build_vocab_files(cat_example_df, categorical_field_list)
vocab_files_list[0]

'./vocab/PRINCIPAL_DIAGNOSIS_CODE_vocab.txt'

In [36]:
principal_diagnosis_vocab = tf.feature_column.categorical_column_with_vocabulary_file(
            key="PRINCIPAL_DIAGNOSIS_CODE", vocabulary_file = vocab_files_list[0], num_oov_buckets=1)

INFO:tensorflow:vocabulary_size = 6753 in PRINCIPAL_DIAGNOSIS_CODE is inferred from the number of elements in the vocabulary_file ./vocab/PRINCIPAL_DIAGNOSIS_CODE_vocab.txt.

In [37]:
dims = 10
cat_embedded = tf.feature_column.embedding_column(principal_diagnosis_vocab, dimension=dims)

In [38]:
categorical_tf_ds_batch = next(iter(categorical_tf_ds))[0]

In [39]:
demo(cat_embedded, categorical_tf_ds_batch)

tf.Tensor(
[[ 0.2701806  -0.16674013  0.3290668  -0.30568475 -0.354516    0.4489967
   0.08725216 -0.18853635 -0.2040914   0.0055417 ]
 [-0.2702217   0.20892164 -0.06639776  0.29391012 -0.02518475 -0.24428943
  -0.1000441  -0.31422147 -0.17913456 -0.00446709]
 [ 0.42692903  0.26062182 -0.16346067  0.17727096  0.4289757  -0.11991581
  -0.06989768  0.11290888 -0.2413592  -0.3139113 ]
 [-0.14939792  0.21454832  0.1519819  -0.29921407 -0.19525753 -0.36112309
   0.06664905  0.17553411 -0.00410633  0.12989679]
 [ 0.14159858  0.41298297  0.04518313 -0.00082355 -0.36582446 -0.01326367
  -0.44627416  0.30800658  0.05168959  0.17729764]
 [-0.04601343 -0.14669093  0.5969889  -0.26773933 -0.308037   -0.36508462
   0.36323965 -0.32020313  0.04629043  0.2843446 ]
 [ 0.02841024  0.40962622  0.09887064 -0.14848216  0.02918675 -0.355546
   0.04057723  0.22947547  0.29895058  0.33513606]
 [ 0.12969686  0.522236    0.00766136 -0.45472318  0.32575396  0.05693621
  -0.1453098  -0.18577266 -0.5722788  -0.09829599]
 [-0.07326403 -0.2975315   0.03631013  0.04441993  0.272771   -0.14532241
  -0.07073091 -0.36437866 -0.17571099 -0.22319819]
 [ 0.28694707 -0.34642437 -0.15255553 -0.4681243  -0.22075795 -0.01928104
  -0.24212296 -0.03667009  0.20195219  0.01257635]
 [-0.62753737 -0.11920308  0.4702035   0.23255628 -0.08055998 -0.18642843
  -0.31978485 -0.3036223  -0.28391305  0.31206176]
 [ 0.09380868  0.05182893 -0.06845147  0.39591807  0.13696133  0.06818834
  -0.32204866 -0.05024338  0.46492273 -0.09956717]
 [-0.03102507 -0.09930607 -0.045911    0.241555   -0.15573782 -0.10625795
  -0.2780866  -0.04934732 -0.37036696  0.23725641]
 [-0.15129107 -0.19421045  0.2947499   0.36417702  0.29008836 -0.12417743
  -0.1747578   0.538592   -0.18295899  0.31564158]
 [-0.01037399  0.2601565  -0.09280774 -0.10450308  0.44590434  0.16321267
   0.3667691  -0.03998883  0.51706904 -0.34177813]
 [-0.5978069   0.22093533  0.03661959 -0.1146699   0.1767721  -0.26020318
   0.28455186  0.4884495  -0.53989214 -0.04925409]
 [-0.25945437  0.05737124 -0.62331766 -0.20878795 -0.06025986 -0.39043683
  -0.43414125 -0.28397113 -0.47983798  0.00861825]
 [ 0.22936939  0.19179969 -0.42199543  0.15584245  0.36698195 -0.03332791
   0.08696597  0.4828618   0.15940814  0.23852976]
 [-0.2099452  -0.09990603  0.5545084   0.06605734  0.00553451 -0.00098864
   0.54068696 -0.22005852 -0.3084998  -0.19666871]
 [ 0.3681555   0.23433092  0.09839787  0.10311177  0.01011102  0.11356158
   0.51231146  0.32117337 -0.437246    0.06744014]
 [ 0.20063376  0.1594305   0.02943337  0.27464846  0.11549417 -0.00164988
   0.10742798  0.15237133 -0.10848348 -0.06923036]
 [ 0.22040808  0.43636167  0.46086016  0.05095957 -0.01824611  0.54084265
   0.38454813 -0.1962072  -0.2626986  -0.1945683 ]
 [ 0.06245439  0.5435683   0.09585883  0.14627907 -0.6271372   0.11865109
  -0.17950244  0.5060321   0.44226545  0.1260174 ]
 [ 0.563982    0.22726715  0.31820273  0.34414247 -0.2397299  -0.08471094
  -0.02831165  0.51267797  0.13630946  0.26457697]
 [ 0.36957622  0.5273707   0.5195293  -0.19141906  0.03829581 -0.11978099
   0.51529145 -0.34770018 -0.14231844 -0.26979175]
 [ 0.33844537  0.21235435 -0.07791152  0.3438208  -0.51174355 -0.32383633
  -0.04255868  0.02991231  0.49922583  0.4925777 ]
 [-0.23069921  0.37067392 -0.32757318  0.49971184  0.1566918   0.05528222
  -0.00112481  0.05137988 -0.06426463  0.17761542]
 [-0.2523823   0.45354003  0.16616525  0.27646255  0.06669293  0.17948388
  -0.27684596  0.40102658  0.28618255 -0.47730544]
 [-0.1258337  -0.23050454  0.01648527  0.3245978   0.268173    0.6314744
  -0.22136055  0.43172035  0.07147894 -0.48643962]
 [-0.24187799 -0.2556036  -0.00280221 -0.20221423  0.03028028 -0.10219883
  -0.36908954 -0.4684914   0.12449618 -0.32523602]
 [ 0.4363617  -0.0186426   0.16408917 -0.0701841  -0.05083609 -0.2699691
   0.05854544 -0.23589781  0.03195333  0.09397942]
 [-0.11020883 -0.3464717  -0.22931169 -0.30192322  0.25219658 -0.26599327
  -0.08126899  0.06849617  0.00518728 -0.2697655 ]
 [-0.18354338 -0.61280847  0.25970605  0.09535073  0.26650882 -0.37908736
  -0.35154137 -0.11224805  0.10636649 -0.17841321]
 [ 0.09669836  0.00196395 -0.2726828   0.1318826  -0.5265685   0.00779609
  -0.4014712   0.5299273   0.10968549  0.07975574]
 [-0.42407036  0.39669767 -0.09202198  0.0057465   0.27010375 -0.3482889
  -0.07353906 -0.32811767  0.59039515  0.09059404]
 [ 0.09208615 -0.1575306   0.19890065  0.24460661  0.58592737 -0.37067235
  -0.18636617  0.29675084 -0.38397434  0.4858104 ]
 [-0.20918387 -0.37263742  0.47809368  0.17575945  0.4673834   0.250339
   0.09489954  0.2264483   0.03216858 -0.19750355]
 [ 0.12075336  0.134802   -0.3946212  -0.10656997 -0.5559977   0.24029875
   0.30494967 -0.07367209 -0.25609913 -0.251844  ]
 [-0.10796824 -0.41688743 -0.09480582  0.10536516 -0.21673845  0.28032166
   0.32761657 -0.34316024  0.19771518  0.28478965]
 [ 0.16183832 -0.42920628  0.40981036 -0.10593488  0.2814699  -0.32931578
  -0.19070758 -0.3138717   0.26895836 -0.33994994]
 [-0.25137386  0.07716062 -0.3052093  -0.17835423  0.09835853 -0.08870991
   0.2773488  -0.21833281 -0.30803573  0.05277833]
 [-0.05109456  0.38753614  0.3085827   0.40855646 -0.46106842  0.39787927
   0.17286636 -0.02299561  0.18833221 -0.02632231]
 [-0.49668622  0.13980782 -0.58434415 -0.15274975 -0.00899756 -0.42264694
  -0.19549511  0.15653552 -0.05342048 -0.11459697]
 [ 0.34086642  0.06738011  0.08692539 -0.10197737  0.3604935  -0.13938102
   0.24867266 -0.12338356 -0.24506386 -0.206899  ]
 [ 0.28489667  0.22193581 -0.03304505  0.05435933  0.46183598 -0.07007901
   0.5032216   0.49976164  0.09517998  0.34390515]
 [-0.49115092 -0.28152    -0.38576064  0.17119901  0.43016547  0.35279477
  -0.46180663  0.23058893  0.62018615 -0.40479836]
 [ 0.33021915 -0.15699331  0.20428176  0.12486725 -0.11174897 -0.3384271
   0.29896256 -0.41494444 -0.16295755  0.24201083]
 [-0.19555713  0.04865479 -0.39767644 -0.29222634  0.11092392  0.16040982
   0.32405993  0.13808839  0.11124957  0.5153824 ]
 [-0.1470131   0.2150406  -0.13030197 -0.04201473 -0.24260542 -0.06453844
   0.03668988 -0.07649905  0.04596245  0.03061874]
 [ 0.17704192  0.24927703 -0.24895985 -0.29010224  0.07743979  0.40891853
  -0.13193275 -0.4869013  -0.05042635  0.04814562]
 [ 0.2634368  -0.5909758   0.308943    0.05875028  0.00798876  0.34627253
   0.00618182  0.19990425  0.21071318 -0.19906779]
 [ 0.21096456  0.21402562  0.05151085 -0.1176165   0.30959752  0.05804597
  -0.19937381  0.22209957  0.14827165  0.5107819 ]
 [-0.15541877 -0.04020003  0.2228558  -0.02949227 -0.33367878  0.09355485
  -0.2689181   0.24037519 -0.10090029 -0.3934177 ]
 [ 0.31589198 -0.5063544  -0.49518916  0.17168775  0.09671081  0.25812867
  -0.03954012  0.19501732  0.08753959  0.02158807]
 [ 0.464757    0.6307811  -0.00444644 -0.18815315  0.0561354  -0.1111392
   0.22099821 -0.02204342  0.07352994 -0.25048816]
 [ 0.3552325  -0.22206935  0.21177158  0.58297014 -0.04755881 -0.15159892
   0.04502749  0.15888563  0.0047917   0.53889155]
 [-0.28071997  0.05972225  0.53015196  0.57945865 -0.06291251 -0.11529295
   0.26482758 -0.2609641   0.44254187  0.32767892]
 [-0.3743848   0.22370596 -0.06709018 -0.10530142 -0.41646692  0.11800917
  -0.0724887   0.3287755  -0.09795443 -0.44506454]
 [-0.13541348  0.34250873  0.1397102  -0.46404392  0.17364319  0.20890164
   0.18032125  0.2866025  -0.32145584 -0.31409454]
 [ 0.00222795  0.15960051 -0.0040967  -0.45646277  0.04618339 -0.2836795
   0.55585194  0.20631465 -0.53822315 -0.3202856 ]
 [ 0.00583499  0.21545643 -0.3927715   0.08960935 -0.10706739 -0.37257397
   0.03713034 -0.29601055 -0.18142933 -0.19524194]
 [-0.28111318 -0.28497764  0.24986024 -0.15508065 -0.35182017 -0.16807939
  -0.4291927   0.2833251   0.3157497   0.5138838 ]
 [-0.10309302 -0.32939854  0.13204266 -0.2225465   0.52614033  0.49269223
   0.16003583  0.18450123  0.3533362  -0.23776631]
 [-0.61229426 -0.42785677 -0.28265056  0.39283028 -0.3631367   0.30132118
  -0.3448558   0.28850657 -0.02407267  0.43063533]], shape=(64, 10), dtype=float32)

Example of one transformed row:
[ 0.2701806  -0.16674013  0.3290668  -0.30568475 -0.354516    0.4489967
  0.08725216 -0.18853635 -0.2040914   0.0055417 ]